// Code generated by scorix.
package analysis

import (
	"context"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/tradalab/scorix/app"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"github.com/tradalab/rdms/pkg/redisscan"
)

const (
	defaultScanCount  = 5000
	defaultSampleSize = 10000
	topKeyCount       = 50
	progressInterval  = 250 * time.Millisecond
	enrichBatch       = 500
	modeFast          = "fast"
	modeSampled       = "sampled"
	modeFull          = "full"
	sourceKeysizes    = "keysizes"
	sourceScan        = "scan"
	recencyFreq       = "freq"
	recencyIdle       = "idle"
)

type ProfileLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewProfileLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ProfileLogic {
	return &ProfileLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *ProfileLogic) Profile(req *types.AnalysisProfileReq, out app.Sink[types.AnalysisProfileEvent]) error {
	cli, err := l.svcCtx.RedisManager.Get(req.ConnectionId, int(req.DatabaseIndex))
	if err != nil {
		return err
	}

	mode := strings.ToLower(strings.TrimSpace(req.Mode))
	if mode != modeSampled && mode != modeFull {
		mode = modeFast
	}

	ev := types.AnalysisProfileEvent{Phase: "info", Warnings: []string{}}
	l.collectInfo(cli.Rdb, &ev)

	if err := out.Send(&ev); err != nil {
		return err
	}
	if mode == modeFast {
		ev.Phase = "done"
		return out.Send(&ev)
	}

	return l.walk(cli.Rdb, req, mode, ev, out)
}

func (l *ProfileLogic) collectInfo(rdb redis.UniversalClient, ev *types.AnalysisProfileEvent) {
	nodes := redisscan.Masters(l.ctx, rdb)

	var rss int64
	for _, node := range nodes {
		if ev.RedisVersion == "" {
			if raw, err := node.Client.Info(l.ctx, "server").Result(); err == nil {
				ev.RedisVersion = infoField(raw, "redis_version")
			}
		}
		raw, err := node.Client.Info(l.ctx, "memory").Result()
		if err != nil {
			continue
		}
		ev.Memory.Used += infoInt(raw, "used_memory")
		ev.Memory.Peak += infoInt(raw, "used_memory_peak")
		ev.Memory.Dataset += infoInt(raw, "used_memory_dataset")
		ev.Memory.Overhead += infoInt(raw, "used_memory_overhead")
		ev.Memory.Maxmemory += infoInt(raw, "maxmemory")
		rss += infoInt(raw, "used_memory_rss")
		if ev.Memory.Policy == "" {
			ev.Memory.Policy = infoField(raw, "maxmemory_policy")
		}
	}
	if ev.Memory.Used > 0 && rss > 0 {
		ev.Memory.Fragmentation = float64(rss) / float64(ev.Memory.Used)
	}
	if ev.Memory.Policy == "" {
		if vals, err := rdb.ConfigGet(l.ctx, "maxmemory-policy").Result(); err == nil {
			ev.Memory.Policy = vals["maxmemory-policy"]
		}
	}

	// OBJECT FREQ and OBJECT IDLETIME exclude each other by eviction policy.
	ev.RecencyMetric = recencyIdle
	if strings.Contains(ev.Memory.Policy, "lfu") {
		ev.RecencyMetric = recencyFreq
	}

	var total, expires int64
	var ttlSum, ttlNodes int64
	for _, node := range nodes {
		t, e, a := l.keyspaceTotals(node.Client)
		total += t
		expires += e
		if a > 0 {
			ttlSum += a
			ttlNodes++
		}
	}
	avgTTL := int64(0)
	if ttlNodes > 0 {
		avgTTL = ttlSum / ttlNodes
	}
	ev.Total = total
	ev.Ttl = types.AnalysisTtlStat{Total: total, WithTtl: expires, AvgTtlMs: avgTTL, Buckets: []types.AnalysisBucket{}}

	ev.Types = []types.AnalysisTypeStat{}
	ev.Distrib = []types.AnalysisSizeDistrib{}
	ev.TopKeys = []types.AnalysisTopKey{}
	ev.Nodes = l.nodeList(nodes)

	var keysizes strings.Builder
	for _, node := range nodes {
		if raw, err := node.Client.Info(l.ctx, "keysizes").Result(); err == nil {
			keysizes.WriteString(raw)
			keysizes.WriteString("\n")
		}
	}
	if raw := keysizes.String(); strings.Contains(raw, "distrib") {
		types_, distrib, counted := parseKeysizes(raw)
		if len(types_) > 0 {
			ev.Types = types_
			ev.Distrib = distrib
			ev.DistribSource = sourceKeysizes
			// The histogram omits module types (RedisJSON) silently, so the shortfall
			// against DBSIZE is surfaced rather than left invisible.
			if total > counted {
				ev.Types = append(ev.Types, types.AnalysisTypeStat{Kind: "other", Keys: total - counted})
				ev.Warnings = append(ev.Warnings, fmt.Sprintf(
					"%d key(s) are of a module type (e.g. RedisJSON) and are not counted by INFO keysizes; shown as \"other\".",
					total-counted))
			}
		}
	}
	if ev.DistribSource == "" {
		ev.Warnings = append(ev.Warnings,
			"This server has no INFO keysizes section (Redis 8+); type distribution needs a scan.")
	}
}

func (l *ProfileLogic) keyspaceTotals(rdb redis.UniversalClient) (total, expires, avgTTL int64) {
	raw, err := rdb.Info(l.ctx, "keyspace").Result()
	if err != nil {
		return 0, 0, 0
	}
	var ttlSum, ttlDbs int64
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "db") || !strings.Contains(line, ":") {
			continue
		}
		for _, part := range strings.Split(line[strings.Index(line, ":")+1:], ",") {
			k, v, ok := strings.Cut(part, "=")
			if !ok {
				continue
			}
			n, _ := strconv.ParseInt(strings.TrimSpace(v), 10, 64)
			switch strings.TrimSpace(k) {
			case "keys":
				total += n
			case "expires":
				expires += n
			case "avg_ttl":
				if n > 0 {
					ttlSum += n
					ttlDbs++
				}
			}
		}
	}
	if ttlDbs > 0 {
		avgTTL = ttlSum / ttlDbs
	}
	return total, expires, avgTTL
}

func (l *ProfileLogic) walk(rdb redis.UniversalClient, req *types.AnalysisProfileReq, mode string, ev types.AnalysisProfileEvent, out app.Sink[types.AnalysisProfileEvent]) error {
	scanCount := int64(defaultScanCount)
	limit := int64(0)
	if mode == modeSampled {
		limit = req.SampleSize
		if limit <= 0 {
			limit = defaultSampleSize
		}
	}

	st := &walkState{
		recency: ev.RecencyMetric,
		byKind:  map[string]*types.AnalysisTypeStat{},
		ttlBuck: map[string]int64{},
	}
	ev.Phase = "scan"
	last := time.Now()

	scanOne := func(node redis.UniversalClient) error {
		var cursor uint64
		for {
			if err := l.ctx.Err(); err != nil {
				return err
			}
			keys, next, err := node.Scan(l.ctx, cursor, "*", scanCount).Result()
			if err != nil {
				return err
			}
			cursor = next
			for start := 0; start < len(keys); start += enrichBatch {
				end := min(start+enrichBatch, len(keys))
				if err := l.enrich(node, keys[start:end], st); err != nil {
					return err
				}
				if limit > 0 && st.scanned >= limit {
					st.truncated = true
					return nil
				}
			}
			if time.Since(last) >= progressInterval {
				last = time.Now()
				snap := ev
				st.fill(&snap)
				if err := out.Send(&snap); err != nil {
					return err
				}
			}
			if cursor == 0 {
				return nil
			}
		}
	}

	// Sequential: ForEachMaster runs a goroutine per master and would race walkState.
	for _, node := range redisscan.Masters(l.ctx, rdb) {
		if err := scanOne(node.Client); err != nil {
			if st.truncated {
				break
			}
			return err
		}
		if st.truncated {
			break
		}
	}

	st.fill(&ev)
	ev.Phase = "done"
	ev.Truncated = st.truncated
	if st.truncated {
		ev.Warnings = append(ev.Warnings, fmt.Sprintf(
			"Sampled %d of %d keys - \"largest keys\" is the largest within that sample, not the largest in the keyspace.",
			st.scanned, ev.Total))
	}
	return out.Send(&ev)
}

type walkState struct {
	recency   string // freq | idle - never both, see collectInfo
	scanned   int64
	truncated bool
	byKind    map[string]*types.AnalysisTypeStat
	top       []types.AnalysisTopKey
	ttlBuck   map[string]int64
}

func (l *ProfileLogic) enrich(node redis.UniversalClient, keys []string, st *walkState) error {
	pipe := node.Pipeline()
	typeCmds := make([]*redis.StatusCmd, len(keys))
	ttlCmds := make([]*redis.DurationCmd, len(keys))
	sizeCmds := make([]*redis.IntCmd, len(keys))
	freqCmds := make([]*redis.IntCmd, len(keys))
	idleCmds := make([]*redis.DurationCmd, len(keys))
	for i, k := range keys {
		typeCmds[i] = pipe.Type(l.ctx, k)
		ttlCmds[i] = pipe.PTTL(l.ctx, k)
		sizeCmds[i] = pipe.MemoryUsage(l.ctx, k)
		switch st.recency {
		case recencyFreq:
			freqCmds[i] = pipe.ObjectFreq(l.ctx, k)
		case recencyIdle:
			idleCmds[i] = pipe.ObjectIdleTime(l.ctx, k)
		}
	}
	if _, err := pipe.Exec(l.ctx); err != nil && err != redis.Nil {
		return err
	}

	for i, k := range keys {
		kind, err := typeCmds[i].Result()
		if err != nil {
			continue // key vanished mid-walk
		}
		kind = strings.ToLower(kind)
		st.scanned++

		size, _ := sizeCmds[i].Result()
		stat, ok := st.byKind[kind]
		if !ok {
			stat = &types.AnalysisTypeStat{Kind: kind}
			st.byKind[kind] = stat
		}
		stat.Keys++
		stat.Bytes += size

		ttl, _ := ttlCmds[i].Result()
		st.ttlBuck[ttlBucket(ttl)]++

		ttlMs := ttl.Milliseconds()
		if ttl < 0 {
			ttlMs = -1
		}

		recency := int64(-1)
		if freqCmds[i] != nil {
			if v, err := freqCmds[i].Result(); err == nil {
				recency = v
			}
		} else if idleCmds[i] != nil {
			if v, err := idleCmds[i].Result(); err == nil {
				recency = int64(v.Seconds())
			}
		}

		if size > 0 {
			st.top = append(st.top, types.AnalysisTopKey{Key: k, Kind: kind, Bytes: size, TtlMs: ttlMs, Recency: recency})
			if len(st.top) >= topKeyCount*20 {
				st.trimTop()
			}
		}
	}
	return nil
}

func (st *walkState) trimTop() {
	sort.Slice(st.top, func(i, j int) bool { return st.top[i].Bytes > st.top[j].Bytes })
	if len(st.top) > topKeyCount {
		st.top = st.top[:topKeyCount:topKeyCount]
	}
}

func (st *walkState) fill(ev *types.AnalysisProfileEvent) {
	st.trimTop()
	ev.Scanned = st.scanned
	ev.TopKeys = append([]types.AnalysisTopKey{}, st.top...)

	kinds := make([]string, 0, len(st.byKind))
	for k := range st.byKind {
		kinds = append(kinds, k)
	}
	sort.Strings(kinds) // stable order: the chart must not reshuffle between frames
	stats := make([]types.AnalysisTypeStat, 0, len(kinds))
	for _, k := range kinds {
		stats = append(stats, *st.byKind[k])
	}
	if len(stats) > 0 {
		ev.Types = stats
		if ev.DistribSource == "" {
			ev.DistribSource = sourceScan
		}
	}

	ev.Ttl.Buckets = bucketsOf(st.ttlBuck, ttlBucketOrder)
}

func (l *ProfileLogic) nodeList(nodes []redisscan.Node) []types.AnalysisNode {
	out := []types.AnalysisNode{}
	if len(nodes) < 2 {
		return out // a single node is the whole instance; showing "1 node" says nothing
	}
	for _, n := range nodes {
		size, _ := n.Client.DBSize(l.ctx).Result()
		out = append(out, types.AnalysisNode{Addr: n.Addr, Keys: size})
	}
	return out
}

func parseKeysizes(raw string) (stats []types.AnalysisTypeStat, distrib []types.AnalysisSizeDistrib, counted int64) {
	keys := map[string]int64{}
	buckets := map[string]map[string]int64{}
	units := map[string]string{}

	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		name, payload, ok := strings.Cut(line, ":")
		if !ok || !strings.Contains(name, "_distrib_") {
			continue
		}
		_, rest, _ := strings.Cut(name, "_distrib_")
		kind, metric, ok := strings.Cut(rest, "_")
		if !ok {
			continue
		}
		unit := "items"
		if metric == "sizes" {
			unit = "bytes"
		}
		units[kind] = unit
		if buckets[kind] == nil {
			buckets[kind] = map[string]int64{}
		}
		for _, pair := range strings.Split(payload, ",") {
			label, cnt, ok := strings.Cut(pair, "=")
			if !ok {
				continue
			}
			n, err := strconv.ParseInt(strings.TrimSpace(cnt), 10, 64)
			if err != nil {
				continue
			}
			buckets[kind][strings.TrimSpace(label)] += n
			keys[kind] += n
			counted += n
		}
	}

	names := make([]string, 0, len(buckets))
	for k := range buckets {
		names = append(names, k)
	}
	sort.Strings(names)
	for _, k := range names {
		stats = append(stats, types.AnalysisTypeStat{Kind: singularKind(k), Keys: keys[k]})
		distrib = append(distrib, types.AnalysisSizeDistrib{
			Kind:    singularKind(k),
			Unit:    units[k],
			Buckets: bucketsOf(buckets[k], sizeBucketLess),
		})
	}
	return stats, distrib, counted
}

func singularKind(k string) string {
	switch k {
	case "strings":
		return "string"
	case "lists":
		return "list"
	case "hashes":
		return "hash"
	case "sets":
		return "set"
	case "zsets":
		return "zset"
	}
	return k
}

func bucketsOf(m map[string]int64, less func(a, b string) bool) []types.AnalysisBucket {
	labels := make([]string, 0, len(m))
	for k := range m {
		labels = append(labels, k)
	}
	sort.Slice(labels, func(i, j int) bool { return less(labels[i], labels[j]) })
	out := make([]types.AnalysisBucket, 0, len(labels))
	for _, k := range labels {
		out = append(out, types.AnalysisBucket{Label: k, Count: m[k]})
	}
	return out
}

// Labels carry a magnitude suffix, so lexical order would put "16K" before "8".
func sizeBucketLess(a, b string) bool { return bucketValue(a) < bucketValue(b) }

func bucketValue(s string) int64 {
	mult := int64(1)
	switch {
	case strings.HasSuffix(s, "K"):
		mult, s = 1<<10, strings.TrimSuffix(s, "K")
	case strings.HasSuffix(s, "M"):
		mult, s = 1<<20, strings.TrimSuffix(s, "M")
	case strings.HasSuffix(s, "G"):
		mult, s = 1<<30, strings.TrimSuffix(s, "G")
	case strings.HasSuffix(s, "T"):
		mult, s = 1<<40, strings.TrimSuffix(s, "T")
	}
	n, _ := strconv.ParseInt(s, 10, 64)
	return n * mult
}

var ttlOrder = map[string]int{
	"none": 0, "<1m": 1, "<1h": 2, "<1d": 3, "<7d": 4, "<30d": 5, ">=30d": 6,
}

func ttlBucketOrder(a, b string) bool { return ttlOrder[a] < ttlOrder[b] }

func ttlBucket(d time.Duration) string {
	switch {
	case d < 0:
		return "none"
	case d < time.Minute:
		return "<1m"
	case d < time.Hour:
		return "<1h"
	case d < 24*time.Hour:
		return "<1d"
	case d < 7*24*time.Hour:
		return "<7d"
	case d < 30*24*time.Hour:
		return "<30d"
	default:
		return ">=30d"
	}
}

func infoField(raw, key string) string {
	for _, line := range strings.Split(raw, "\n") {
		k, v, ok := strings.Cut(strings.TrimSpace(line), ":")
		if ok && k == key {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

func infoInt(raw, key string) int64 {
	n, _ := strconv.ParseInt(infoField(raw, key), 10, 64)
	return n
}

func infoFloat(raw, key string) float64 {
	f, _ := strconv.ParseFloat(infoField(raw, key), 64)
	return f
}
