// Code generated by scorix.
package client

import (
	"context"
	"fmt"
	"strings"

	"github.com/redis/go-redis/v9"
	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
)

type KeyValueUpdateLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeyValueUpdateLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeyValueUpdateLogic {
	return &KeyValueUpdateLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeyValueUpdateLogic) KeyValueUpdate(params *types.ClientKeyValueUpdateReq) (*types.Empty, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	switch strings.ToLower(params.Kind) {
	case "string":
		err = cli.Rdb.SetArgs(l.ctx, params.Key, params.Value, redis.SetArgs{KeepTTL: true}).Err()
	case "json", "rejson", "rejson-rl":
		err = cli.Rdb.JSONSet(l.ctx, params.Key, ".", params.Value).Err()
	default:
		return nil, fmt.Errorf("unsupported kind: %s", params.Kind)
	}

	if err != nil {
		return nil, err
	}

	return &types.Empty{}, nil
}
