// Code generated by scorix.
package client

import (
	"context"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"github.com/tradalab/rdms/pkg/redisscan"
)

type KeysScanByPrefixLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeysScanByPrefixLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeysScanByPrefixLogic {
	return &KeysScanByPrefixLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeysScanByPrefixLogic) KeysScanByPrefix(params *types.ClientKeysDeleteByPrefixReq) (*types.ClientKeysScanByPrefixRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	match := params.Prefix + "*"
	limit := int64(1000)

	keys, next, err := redisscan.Page(l.ctx, cli.Rdb, redisscan.Cursor{}, match, limit, "")
	if err != nil {
		return nil, err
	}

	return &types.ClientKeysScanByPrefixRes{
		Keys:       keys,
		NextCursor: next.String(),
	}, nil
}
