// Code generated by scorix.
package client

import (
	"context"
	"fmt"

	"github.com/tradalab/scorix/app"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"github.com/tradalab/rdms/pkg/redisscan"
)

type KeysDeleteByPrefixLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewKeysDeleteByPrefixLogic(ctx context.Context, svcCtx *svc.ServiceContext) *KeysDeleteByPrefixLogic {
	return &KeysDeleteByPrefixLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *KeysDeleteByPrefixLogic) KeysDeleteByPrefix(params *types.ClientKeysDeleteByPrefixReq, out app.Sink[types.ClientKeysDeleteProgressEvent]) error {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return err
	}

	progress := func(deleted, total int, status string) error {
		return out.Send(&types.ClientKeysDeleteProgressEvent{
			ConnectionId: params.ConnectionId,
			Prefix:       params.Prefix,
			Deleted:      int64(deleted),
			Total:        int64(total),
			Status:       status,
		})
	}

	if len(params.Keys) > 0 {
		batchSize := 1000
		totalDeleted := 0
		for i := 0; i < len(params.Keys); i += batchSize {
			end := i + batchSize
			if end > len(params.Keys) {
				end = len(params.Keys)
			}
			batch := params.Keys[i:end]

			if err = cli.Rdb.Del(l.ctx, batch...).Err(); err != nil {
				return err
			}
			totalDeleted += len(batch)

			if err = progress(totalDeleted, len(params.Keys), "processing"); err != nil {
				return err
			}
		}

		return progress(totalDeleted, len(params.Keys), "done")
	}

	if params.Prefix == "" {
		return fmt.Errorf("prefix or keys must be provided")
	}

	match := params.Prefix + "*"
	batchSize := int64(1000)
	totalDeleted := 0

	err = redisscan.Each(l.ctx, cli.Rdb, match, batchSize, func(keys []string) error {
		if err := cli.Rdb.Del(l.ctx, keys...).Err(); err != nil {
			return err
		}
		totalDeleted += len(keys)
		return progress(totalDeleted, 0, "processing")
	})
	if err != nil {
		return err
	}

	return progress(totalDeleted, 0, "done")
}
