// Code generated by scorix.
package client

import (
	"context"
	"strings"

	"github.com/tradalab/rdms/internal/svc"
	"github.com/tradalab/rdms/internal/types"
	"github.com/tradalab/rdms/pkg/redisscan"
)

type LoadAllKeysLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
}

func NewLoadAllKeysLogic(ctx context.Context, svcCtx *svc.ServiceContext) *LoadAllKeysLogic {
	return &LoadAllKeysLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
	}
}

func (l *LoadAllKeysLogic) LoadAllKeys(params *types.ClientLoadAllKeysReq) (*types.ClientLoadAllKeysRes, error) {
	cli, err := l.svcCtx.RedisManager.Get(params.ConnectionId, int(params.DatabaseIndex))
	if err != nil {
		return nil, err
	}

	pattern := params.Prefix
	if !strings.Contains(pattern, "*") {
		pattern += "*"
	}

	keys, next, err := redisscan.Page(l.ctx, cli.Rdb, redisscan.ParseCursor(params.Cursor), pattern, params.Count, "")
	if err != nil {
		return nil, err
	}

	return &types.ClientLoadAllKeysRes{
		Keys:   keys,
		Cursor: next.String(),
	}, nil
}
